language: cpp
os: linux
stages:
    - name: deploy
      if: branch = master
    - name: before_script
      if: branch = master
jobs:
    include:
    - name: "macOS Build"
      os: osx
      compiler: clang
      osx_image: xcode10.3
      script:
        - bash scripts/build.macos.release.sh
      before_deploy:
        - tar czf subconverter_darwin64.tar.gz subconverter
      deploy:
        provider: releases
        token: "$GITHUB_OAUTH_TOKEN"
        file: "subconverter_darwin64.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - name: "Linux x86 Build"
      services: docker
      script:
        - docker run --rm -v $TRAVIS_BUILD_DIR:/root/workdir multiarch/alpine:x86-edge /bin/sh -c "apk add bash git && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
      before_deploy:
        - tar czf subconverter_linux32.tar.gz subconverter/
      deploy:
        provider: releases
        token: "$GITHUB_OAUTH_TOKEN"
        file: "subconverter_linux32.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - name: "Linux x86_64 Build"
      services: docker
      script:
        - docker run -v $TRAVIS_BUILD_DIR:/root/workdir multiarch/alpine:amd64-edge /bin/sh -c "apk add bash git && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
      before_deploy:
        - tar czf subconverter_linux64.tar.gz subconverter/
      deploy:
        provider: releases
        token: "$GITHUB_OAUTH_TOKEN"
        file: "subconverter_linux64.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - name: "Linux ARMHF Build"
      services: docker
      arch: arm64
      script:
        - docker run --rm -v $TRAVIS_BUILD_DIR:/root/workdir multiarch/alpine:armhf-edge /bin/sh -c "apk add bash git && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
      before_deploy:
        - tar czf subconverter_armhf.tar.gz subconverter/
      deploy:
        provider: releases
        token: "$GITHUB_OAUTH_TOKEN"
        file: "subconverter_armhf.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - name: "Linux ARM64 Build"
      services: docker
      arch: arm64
      script:
        - docker run -v $TRAVIS_BUILD_DIR:/root/workdir multiarch/alpine:aarch64-edge /bin/sh -c "apk add bash git && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
      before_deploy:
        - tar czf subconverter_aarch64.tar.gz subconverter/
      deploy:
        provider: releases
        token: "$GITHUB_OAUTH_TOKEN"
        file: "subconverter_aarch64.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true    
